### ISSUE TITLE
遇到报错

### ISSUE THREAD

**Issue by TNXG** [W4J1e/picgo-plugin-dogecloud#8]
```
------Error Stack Begin------
TypeError: Cannot read property 'credentials' of undefined
    at Object.handle (C:\Users\mcmin\AppData\Roaming\picgo\node_modules\picgo-plugin-dogecloud\dist\index.js:135:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (C:\Program Files\PicGo\resources\app.asar\background.js:36:31625)
-------Error Stack End------- 
```
想问问大佬这是怎么回事

**Comment by W4J1e** [comment]
确定配置项填对了吗，尤其是 `AccessKey`和`SecretKey`

**Comment by TNXG** [comment]
> 确定配置项填对了吗，尤其是 和`AccessKey``SecretKey`

储存桶这个地方填写`s3Bucket`和`空间名称`提供的值都报错，`AccessKey`和`SecretKey`的填写是正确的

**Comment by W4J1e** [comment]
> 

我这里测试上传一切正常，picgo的日志报错我个人无法很准确定位问题，所以可以反馈一下上传失败时的通知内容。
此外，请确认：
1.存储空间是否为标准型；
2.上传路径填写是否规范。
示例：
![1](https://user-images.githubusercontent.com/74824162/180180653-b20c85d8-9f2c-4d0f-b0df-9bca9133bab1.jpg)

**Comment by TNXG** [comment]
> > 
> 
> 我这里测试上传一切正常，picgo的日志报错我个人无法很准确定位问题，所以可以反馈一下上传失败时的通知内容。 此外，请确认： 1.存储空间是否为标准型； 2.上传路径填写是否规范。 示例： ![1](https://user-images.githubusercontent.com/74824162/180180653-b20c85d8-9f2c-4d0f-b0df-9bca9133bab1.jpg)

![image](https://user-images.githubusercontent.com/69001561/180184882-d39863b3-d755-4a4e-b298-ee8fe53970f8.png)
![image](https://user-images.githubusercontent.com/69001561/180185136-a64ca62f-8936-447e-9314-adfd9474b65b.png)
![image](https://user-images.githubusercontent.com/69001561/180185732-0feb6be9-8f9e-4a7f-a8d9-67999e67a875.png)

**Comment by W4J1e** [comment]
方便远程看一下吗？

**Comment by TNXG** [comment]
> 方便远程看一下吗？
如何配合（）

**Comment by W4J1e** [comment]
加我QQ 892599923

**Comment by W4J1e** [comment]
已解决，请更新版本。
记录一下：问题是因为默认按`-`截取用户填入的`s3bucket`第三个字符段，导致当存储空间带有`-`时无法正确获取s3bucket。
例如：当用户的存储空间名为`test-1`时，`s3bucket`为`s-sz-1234-ming-1-1234567`，插件截取到的为`test`而非`test-1`。
